spring:
  datasource:
    data-username: root
    data-password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: none

#debug: true
server:
  port: 8086
