spring:
  datasource:
    data-username: root
    data-password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: none
  security:
    user:
      name: admin
      password: admin

#debug: true
server:
  port: 8086

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  base-packages: org.seven.mapper
